# Explore here

This dataset includes data on adult's diet, physical activity, and weight status from Behavioral Risk Factor Surveillance System. This data is used for DNPAO's Data, Trends, and Maps database, which provides national and state specific data on obesity, nutrition, physical activity, and breastfeeding.

In [2]:
# Your code here
import pandas as pd
datasetNutri = pd.read_csv('../data/raw/Nutrition__Physical_Activity__and_Obesity_-_Behavioral_Risk_Factor_Surveillance_System.csv')
datasetNutri

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2020,2020,US,National,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,NaN,PA,PA1,Q047,VALUE,59,Race/Ethnicity,Hispanic,RACE,RACEHIS
1,2014,2014,GU,Guam,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(13.444304, 144.793731)",OWS,OWS1,Q036,VALUE,66,Education,High school graduate,EDU,EDUHSGRAD
2,2013,2013,US,National,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,NaN,OWS,OWS1,Q036,VALUE,59,Income,"$50,000 - $74,999",INC,INC5075
3,2013,2013,US,National,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,NaN,OWS,OWS1,Q037,VALUE,59,Income,Data not reported,INC,INCNR
4,2015,2015,US,National,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who achieve at least 300 min...,NaN,Value,...,NaN,PA,PA1,Q045,VALUE,59,Income,"Less than $15,000",INC,INCLESS15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93244,2022,2022,WY,Wyoming,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(43.23554134300048, -108.10983035299967)",OWS,OWS1,Q037,VALUE,56,Income,"Less than $15,000",INC,INCLESS15
93245,2022,2022,WY,Wyoming,BRFSS,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(43.23554134300048, -108.10983035299967)",PA,PA1,Q047,VALUE,56,Education,Less than high school,EDU,EDUHS
93246,2022,2022,WY,Wyoming,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(43.23554134300048, -108.10983035299967)",OWS,OWS1,Q036,VALUE,56,Age (years),35 - 44,AGEYR,AGEYR3544
93247,2022,2022,WY,Wyoming,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(43.23554134300048, -108.10983035299967)",OWS,OWS1,Q037,VALUE,56,Income,"$35,000 - $49,999",INC,INC3550
93248,2022,2022,WY,Wyoming,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(43.23554134300048, -108.10983035299967)",OWS,OWS1,Q036,VALUE,56,Education,Less than high school,EDU,EDUHS

In [5]:
datasetNutri.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

In [6]:
# Your code here
import pandas as pd
datasetelectric = pd.read_csv('../data/raw/Electric_Vehicle_Population_Size_History_By_County.csv')
datasetelectric

,Date,County,State,Vehicle Primary Use,Battery Electric Vehicles (BEVs),Plug-In Hybrid Electric Vehicles (PHEVs),Electric Vehicle (EV) Total,Non-Electric Vehicle Total,Total Vehicles,Percent Electric Vehicles
0,April 30 2022,Wahkiakum,WA,Truck,0,0,0,1815,1815,0.00
1,May 31 2017,Adams,WA,Truck,0,0,0,5079,5079,0.00
2,October 31 2019,Collin,TX,Passenger,2,1,3,142,145,2.07
3,January 31 2024,Franklin,WA,Truck,10,0,10,20616,20626,0.05
4,February 28 2018,Grays Harbor,WA,Truck,0,0,0,20109,20109,0.00
...,...,...,...,...,...,...,...,...,...,...
21202,March 31 2021,Carson City,NV,Passenger,1,0,1,12,13,7.69
21203,February 28 2023,Adams,WA,Passenger,21,11,32,13009,13041,0.25
21204,June 30 2020,Douglas,NE,Passenger,0,1,1,55,56,1.79
21205,February 29 2020,Chelan,WA,Passenger,216,78,294,54600,54894,0.54
21206,July 31 2021,Chesapeake,VA,Passenger,0,3,3,411,414,0.72

In [1]:
# Your code here
import pandas as pd
datasetcronic = pd.read_csv('../data/raw/U.S._Chronic_Disease_Indicators.csv')
datasetcronic

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,TopicID,QuestionID,ResponseID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2019,2019,GA,Georgia,BRFSS,Disability,Adults with any disability,NaN,%,Crude Prevalence,...,DIS,DIS01,NaN,CRDPREV,AGE,AGE65P,NaN,NaN,NaN,NaN
1,2019,2019,GU,Guam,BRFSS,Arthritis,Arthritis among adults,NaN,%,Crude Prevalence,...,ART,ART01,NaN,CRDPREV,SEX,SEXF,NaN,NaN,NaN,NaN
2,2019,2019,GU,Guam,BRFSS,Immunization,Influenza vaccination among adults,NaN,%,Crude Prevalence,...,IMM,IMM01,NaN,CRDPREV,SEX,SEXM,NaN,NaN,NaN,NaN
3,2019,2019,ME,Maine,BRFSS,Diabetes,Diabetes among adults,NaN,%,Crude Prevalence,...,DIA,DIA01,NaN,CRDPREV,SEX,SEXM,NaN,NaN,NaN,NaN
4,2019,2019,NV,Nevada,NVSS,Health Status,Life expectancy at birth,NaN,Years,Number,...,HEA,HEA06,NaN,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311740,2022,2022,VA,Virginia,BRFSS,"Nutrition, Physical Activity, and Weight Status",Obesity among adults,NaN,%,Age-adjusted Prevalence,...,NPAW,NPW14,NaN,AGEADJPREV,RACE,MRC,NaN,NaN,NaN,NaN
311741,2022,2022,WA,Washington,BRFSS,Sleep,Short sleep duration among adults,NaN,%,Crude Prevalence,...,SLEP,SLP03,NaN,CRDPREV,AGE,AGE65P,NaN,NaN,NaN,NaN
311742,2022,2022,UT,Utah,BRFSS,Immunization,Pneumococcal vaccination among adults aged 65 ...,NaN,%,Crude Prevalence,...,IMM,IMM04,NaN,CRDPREV,RACE,AIAN,NaN,NaN,NaN,NaN
311743,2022,2022,VI,Virgin Islands,BRFSS,Mental Health,Frequent mental distress among adults,NaN,%,Crude Prevalence,...,MEN,MEN05,NaN,CRDPREV,SEX,SEXM,NaN,NaN,NaN,NaN
311744,2022,2022,WI,Wisconsin,BRFSS,Immunization,Influenza vaccination among adults,NaN,%,Age-adjusted Prevalence,...,IMM,IMM01,NaN,AGEADJPREV,SEX,SEXM,NaN,NaN,NaN,NaN

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17) 
  
# data (as pandas dataframes) 
X = breast_cancer_wisconsin_diagnostic.data.features 
y = breast_cancer_wisconsin_diagnostic.data.targets 
  
# metadata 
print(breast_cancer_wisconsin_diagnostic.metadata) 
  
# variable information 
print(breast_cancer_wisconsin_diagnostic.variables)

{'uci_id': 17, 'name': 'Breast Cancer Wisconsin (Diagnostic)', 'repository_url': 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic', 'data_url': 'https://archive.ics.uci.edu/static/public/17/data.csv', 'abstract': 'Diagnostic Wisconsin Breast Cancer Database.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 569, 'num_features': 30, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Diagnosis'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1993, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5DW2B', 'creators': ['William Wolberg', 'Olvi Mangasarian', 'Nick Street', 'W. Street'], 'intro_paper': {'title': 'Nuclear feature extraction for breast tumor diagnosis', 'authors': 'W. Street, W. Wolberg, O. Mangasarian', 'published_in': 'Electronic imaging', 'year': 1993, 'url': 'https://www.semanticscholar.org/paper/53f0fbb425bc14468eb3bf96b2e1d41ba8087f36', 'doi': '10.1117/12.148698'}, 'additional_info': {'summary': 'Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass.  They describe characteristics of the cell nuclei present in the image. A few of the images can be found at http://www.cs.wisc.edu/~street/images/\r\n\r\nSeparating plane described above was obtained using Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree Construction Via Linear Programming." Proceedings of the 4th Midwest Artificial Intelligence and Cognitive Science Society, pp. 97-101, 1992], a classification method which uses linear programming to construct a decision tree.  Relevant features were selected using an exhaustive search in the space of 1-4 features and 1-3 separating planes.\r\n\r\nThe actual linear program used to obtain the separating plane in the 3-dimensional space is that described in: [K. P. Bennett and O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].\r\n\r\nThis database is also available through the UW CS ftp server:\r\nftp ftp.cs.wisc.edu\r\ncd math-prog/cpo-dataset/machine-learn/WDBC/', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '1) ID number\r\n2) Diagnosis (M = malignant, B = benign)\r\n3-32)\r\n\r\nTen real-valued features are computed for each cell nucleus:\r\n\r\n\ta) radius (mean of distances from center to points on the perimeter)\r\n\tb) texture (standard deviation of gray-scale values)\r\n\tc) perimeter\r\n\td) area\r\n\te) smoothness (local variation in radius lengths)\r\n\tf) compactness (perimeter^2 / area - 1.0)\r\n\tg) concavity (severity of concave portions of the contour)\r\n\th) concave points (number of concave portions of the contour)\r\n\ti) symmetry \r\n\tj) fractal dimension ("coastline approximation" - 1)', 'citation': None}}
                  name     role         type demographic description units  \
0                   ID       ID  Categorical        None        None  None
1            Diagnosis   Target  Categorical        None        None  None
2              radius1  Feature   Continuous        None        None  None
3             texture1  Feature   Continuous        None        None  None
4           perimeter1  Feature   Continuous        None        None  None
5                area1  Feature   Continuous        None        None  None
6          smoothness1  Feature   Continuous        None        None  None
7         compactness1  Feature   Continuous        None        None  None
8           concavity1  Feature   Continuous        None        None  None
9      concave_points1  Feature   Continuous        None        None  None
10           symmetry1  Feature   Continuous        None        None  None
11  fractal_dimension1  Feature   Continuous        None        None  None
12             radius2  Feature   Continuous        None        None  None
13            texture2  Feature   Continuous        None        None  None
14          perimeter2  Feature   Continuous        None        None  None
15               area2  Feature   Continuous        None        None  None
16         smoothness2  Feature   Continuous        None        None  None
17        compactness2  Feature   Continuous        None        None  None
18          concavity2  Feature   Continuous        None        None  None
19     concave_points2  Feature   Continuous        None        None  None
20           symmetry2  Feature   Continuous        None        None  None
21  fractal_dimension2  Feature   Continuous        None        None  None
22             radius3  Feature   Continuous        None        None  None
23            texture3  Feature   Continuous        None        None  None
24          perimeter3  Feature   Continuous        None        None  None
25               area3  Feature   Continuous        None        None  None
26         smoothness3  Feature   Continuous        None        None  None
27        compactness3  Feature   Continuous        None        None  None
28          concavity3  Feature   Continuous        None        None  None
29     concave_points3  Feature   Continuous        None        None  None
30           symmetry3  Feature   Continuous        None        None  None
31  fractal_dimension3  Feature   Continuous        None        None  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no
22             no
23             no
24             no
25             no
26             no
27             no
28             no
29             no
30             no
31             no

In [4]:
# Your code here
import pandas as pd
datasetcancer = pd.read_csv('../data/raw/LakeCounty_Health_-4627800489705015123.csv')

datasetcancer

,OBJECTID,ZIP,Colorectal,Lung_Bronc,Breast_Can,Prostate_C,Urinary_Sy,All_Cancer,Shape__Area,Shape__Length
0,1,60002,218.062127,419.666735,399.094836,259.205925,259.205925,2703.147501,1.149062e+09,215525.155184
1,2,60010,258.915706,335.464697,504.322767,499.819885,227.395533,3248.829251,8.027354e+08,178637.109618
2,3,60015,153.435867,230.153801,478.573777,442.041428,222.847331,2922.587952,3.674576e+08,111400.890558
3,4,60020,292.797189,507.515128,214.717939,302.557095,370.876440,3084.130392,1.666177e+08,92363.084625
4,5,60030,221.535432,284.440555,404.780789,322.730629,210.595411,2581.845035,8.455179e+08,247258.224672
5,6,60031,163.502110,221.518987,414.029536,303.270042,160.864979,2217.827004,5.271176e+08,163995.181561
6,7,60035,241.311124,475.919161,553.004659,482.622248,392.130576,3760.431679,3.457929e+08,115796.723819
7,8,60040,55.555556,240.740741,277.777778,185.185185,185.185185,1796.296296,1.780943e+07,25907.372467
8,9,60042,140.252454,315.568022,397.381954,187.003273,187.003273,2267.414680,4.517757e+07,45385.395226
9,10,60044,206.547558,237.529691,557.678405,413.095115,165.238046,3149.850253,2.127777e+08,92539.708731
10,11,60045,258.334958,316.825892,609.280562,497.172938,282.706181,3611.815169,6.214754e+08,161457.245301
11,12,60046,177.859376,258.182966,398.749247,275.395163,197.940274,2340.858889,7.304244e+08,207743.912574
12,13,60047,198.953128,184.742190,362.378911,305.535160,172.899742,2261.907582,9.193818e+08,176981.859420
13,14,60048,276.601557,245.868051,450.758093,331.238902,211.719710,2697.718891,8.190083e+08,196071.573674
14,15,60060,184.467810,197.644083,358.394603,231.902390,184.467810,2174.084908,6.175913e+08,180171.962436
15,16,60061,214.198286,221.848225,367.197062,237.148103,225.673195,2409.730722,2.574212e+08,102713.138127
16,17,60064,188.702982,270.474273,239.023777,245.313876,56.610894,1830.418921,1.399011e+08,90452.895586
17,18,60069,457.776172,578.243585,626.430551,457.776172,421.635947,4505.481267,1.700669e+08,146555.427438
18,19,60073,103.329506,188.617353,211.579465,145.973430,126.291619,1533.541086,5.196587e+08,209118.936758
19,20,60083,173.376999,221.537276,529.763051,356.386053,134.848777,2205.740705,7.282379e+08,164753.217612
20,21,60084,226.885990,340.328985,296.212264,283.607487,302.514653,2596.584105,5.051635e+08,159182.367883
21,22,60085,133.592080,182.810215,203.903701,202.497469,113.904826,1465.294184,3.919074e+08,137038.947754
22,23,60087,212.330325,303.329036,269.204520,254.038068,178.205809,2092.970350,3.898800e+08,163122.611793
23,24,60089,216.429396,317.429781,485.763755,375.144286,216.429396,2991.535206,2.277724e+08,164174.744392
24,25,60096,303.907381,376.266281,405.209841,376.266281,202.604920,2995.658466,1.413737e+08,62444.471661
25,26,60099,220.701832,280.606615,302.676798,264.842198,208.090299,2317.369234,6.262642e+08,188925.390246
26,27,60041,323.512421,496.822646,288.850376,404.390526,381.282496,3200.462161,3.919550e+08,152724.616883